REPORT ZREP_16_LIST_HEADER_AND_FOOTER
  LINE-COUNT 20.

*---------------------------------------------------------------------*
* Program    : ZREP_16_LIST_HEADER_AND_FOOTER
* Title      : List Header and Footer
* Purpose    : Demonstrates a complete Classical ABAP list layout
*              using page headers and footers.
*---------------------------------------------------------------------*
* Description
*---------------------------------------------------------------------*
* This report combines TOP-OF-PAGE and END-OF-PAGE to create a
* structured classical list report.
*
* Topics Covered
* 1. TOP-OF-PAGE
* 2. END-OF-PAGE
* 3. LINE-COUNT
* 4. Page header
* 5. Column header
* 6. Report body
* 7. Page footer
* 8. SY-PAGNO
* 9. SY-DATUM
* 10. SY-UZEIT
*---------------------------------------------------------------------*
* Learning Objectives
*---------------------------------------------------------------------*
* - Build a complete classical list layout.
* - Separate header, body, and footer sections.
* - Create reusable page headers and footers.
* - Use system fields for dynamic report information.
*---------------------------------------------------------------------*

************************************************************************
* Constants
************************************************************************

CONSTANTS:
  gc_line TYPE string VALUE
    '===================================================================='.

************************************************************************
* Global Data
************************************************************************

DATA:
  gv_employee_id TYPE n LENGTH 6,
  gv_employee     TYPE string,
  gv_department   TYPE string,
  gv_status       TYPE string,
  gv_counter      TYPE i.

************************************************************************
* START-OF-SELECTION
************************************************************************

START-OF-SELECTION.

*---------------------------------------------------------------------*
* Report Body
*---------------------------------------------------------------------*

  DO 35 TIMES.

    gv_counter = sy-index.
    gv_employee_id = gv_counter.

    CASE gv_counter MOD 3.

      WHEN 0.
        gv_employee   = 'Employee A'.
        gv_department = 'Finance'.
        gv_status     = 'Active'.

      WHEN 1.
        gv_employee   = 'Employee B'.
        gv_department = 'Sales'.
        gv_status     = 'Active'.

      WHEN 2.
        gv_employee   = 'Employee C'.
        gv_department = 'Production'.
        gv_status     = 'Active'.

    ENDCASE.

    WRITE: / gv_employee_id.
    WRITE AT 15 gv_employee.
    WRITE AT 40 gv_department.
    WRITE AT 60 gv_status.

  ENDDO.

************************************************************************
* TOP-OF-PAGE
************************************************************************
* Creates the header at the beginning of each page.

TOP-OF-PAGE.

  FORMAT INTENSIFIED ON.

  WRITE: / gc_line.
  WRITE: / '                 EMPLOYEE STATUS REPORT' CENTERED.
  WRITE: / gc_line.

  FORMAT INTENSIFIED OFF.

  WRITE: / 'Program :', sy-repid.
  WRITE AT 35 'Page :', sy-pagno.
  WRITE AT 55 'Date :', sy-datum.

  WRITE: / 'Time    :', sy-uzeit.
  WRITE AT 35 'User :', sy-uname.

  SKIP.

*---------------------------------------------------------------------*
* Column Header
*---------------------------------------------------------------------*

  WRITE: / 'ID'.
  WRITE AT 15 'EMPLOYEE'.
  WRITE AT 40 'DEPARTMENT'.
  WRITE AT 60 'STATUS'.

  ULINE.

************************************************************************
* END-OF-PAGE
************************************************************************
* Creates the footer at the end of each page.

END-OF-PAGE.

  SKIP.

  ULINE.

  WRITE: / 'Report Footer'.
  WRITE AT 35 'Page:', sy-pagno.
  WRITE AT 55 'Client:', sy-mandt.

  WRITE: / 'Generated by Classical ABAP Report'.

************************************************************************
* END-OF-SELECTION
************************************************************************

END-OF-SELECTION.

  SKIP 2.
  WRITE: / 'Report processing completed.'.
