REPORT ZREP_15_END_OF_PAGE_EVENT
  LINE-COUNT 15.

*---------------------------------------------------------------------*
* Program    : ZREP_15_END_OF_PAGE_EVENT
* Title      : END-OF-PAGE Event
* Purpose    : Demonstrates the END-OF-PAGE event in a
*              Classical ABAP Report.
*---------------------------------------------------------------------*
* Description
*---------------------------------------------------------------------*
* END-OF-PAGE is triggered when the defined page length is reached.
*
* It is commonly used to display:
* - Page footers
* - Page numbers
* - Report status
* - Summary information
* - Footer separators
*
* LINE-COUNT is used to define the number of lines available on
* each list page.
*
* Topics Covered
* 1. END-OF-PAGE
* 2. LINE-COUNT
* 3. Page footer
* 4. SY-PAGNO
* 5. Automatic page handling
* 6. TOP-OF-PAGE and END-OF-PAGE together
*---------------------------------------------------------------------*
* Learning Objectives
*---------------------------------------------------------------------*
* - Understand the purpose of END-OF-PAGE.
* - Understand the relationship between LINE-COUNT and END-OF-PAGE.
* - Create a reusable page footer.
* - Display dynamic page information.
*---------------------------------------------------------------------*

************************************************************************
* Global Data
************************************************************************

DATA:
  gv_employee_id TYPE n LENGTH 6,
  gv_counter     TYPE i.

************************************************************************
* START-OF-SELECTION
************************************************************************

START-OF-SELECTION.

*---------------------------------------------------------------------*
* Generate Report Data
*---------------------------------------------------------------------*

  DO 30 TIMES.

    gv_counter = sy-index.
    gv_employee_id = gv_counter.

    WRITE: / gv_employee_id.
    WRITE AT 15 'Employee'.
    WRITE AT 35 'Finance'.
    WRITE AT 55 'Active'.

  ENDDO.

************************************************************************
* TOP-OF-PAGE
************************************************************************
* Executed at the beginning of each list page.

TOP-OF-PAGE.

  FORMAT INTENSIFIED ON.

  WRITE: / '============================================================'.
  WRITE: / '                  EMPLOYEE REPORT'.
  WRITE: / '============================================================'.

  FORMAT INTENSIFIED OFF.

  WRITE: / 'Program :', sy-repid.
  WRITE AT 35 'Page :', sy-pagno.
  WRITE AT 55 'Date :', sy-datum.

  SKIP.

  WRITE: / 'ID'.
  WRITE AT 15 'EMPLOYEE'.
  WRITE AT 35 'DEPARTMENT'.
  WRITE AT 55 'STATUS'.

  ULINE.

************************************************************************
* END-OF-PAGE
************************************************************************
* Executed when the defined page length is reached.

END-OF-PAGE.

  SKIP.

  ULINE.

  WRITE: / 'Report Footer'.
  WRITE AT 35 'Page:', sy-pagno.
  WRITE AT 55 'User:', sy-uname.

  WRITE: / 'Generated by Classical ABAP Report'.
